import { DisplayProfile } from "./generateProfile";

export type Stranger = DisplayProfile & {
  id: string;
  replyBank: string[];
};

export const STRANGERS: Stranger[] = [
  {
    id: "s1",
    name: "Rhea",
    age: 24,
    zodiac: "♓ Pisces",
    bio: "An introverted night owl who secretly enjoys deep conversations more than small talk.",
    likes: ["gaming", "music", "dogs", "travel"],
    dislikes: ["dry texting", "small talk"],
    greenFlags: ["Honest", "Funny", "Supportive"],
    redFlags: ["Replies late", "Sleeps at 4AM"],
    conversationStyle: "Deep & reflective",
    communicationType: "Thoughtful communicator",
    conversationEnergy: 4,
    curiosityLevel: 95,
    chaosLevel: 7,
    friendshipPotential: 88,
    humorScore: 6,
    introvertExtrovertPct: 35,
    nightOwlPct: 82,
    empathyPct: 74,
    patiencePct: 60,
    responseSpeed: "Relaxed",
    favoriteTopics: ["late-night thoughts", "music", "travel"],
    conversationStarters: ["What's a belief you've completely changed your mind about?"],
    replyBank: [
      "honestly never thought about it that way",
      "okay wait that's actually a really good point",
      "3am me would have a whole essay about this",
      "lol true. what made you think of that",
      "i feel like i overthink this exact thing weekly",
    ],
  },
  {
    id: "s2",
    name: "Kabir",
    age: 22,
    zodiac: "♌ Leo",
    bio: "Chaotic on purpose, funnier than they let on, and always up for one honest conversation.",
    likes: ["gym", "spontaneous plans", "loud playlists"],
    dislikes: ["flaky plans", "being rushed"],
    greenFlags: ["Funny", "Direct", "Curious"],
    redFlags: ["Too blunt", "Easily distracted"],
    conversationStyle: "Chaotic & spontaneous",
    communicationType: "Direct communicator",
    conversationEnergy: 5,
    curiosityLevel: 70,
    chaosLevel: 9,
    friendshipPotential: 72,
    humorScore: 9,
    introvertExtrovertPct: 78,
    nightOwlPct: 55,
    empathyPct: 50,
    patiencePct: 30,
    responseSpeed: "Instant",
    favoriteTopics: ["sports", "gym", "gaming"],
    conversationStarters: ["What would you do if you won ₹50 crore tomorrow?"],
    replyBank: [
      "wait no way, same",
      "lmaooo okay that's chaotic i respect it",
      "bro i would do the exact opposite",
      "ok your turn, ask me anything",
      "this convo is already better than my last 5 dates",
    ],
  },
  {
    id: "s3",
    name: "Maya",
    age: 27,
    zodiac: "♏ Scorpio",
    bio: "Picks conversations carefully — endlessly curious and a genuinely good listener.",
    likes: ["books", "board games", "quiet mornings"],
    dislikes: ["loud chewing", "unnecessary drama"],
    greenFlags: ["Good listener", "Curious", "Honest"],
    redFlags: ["Overthinks everything"],
    conversationStyle: "Deep & reflective",
    communicationType: "Thoughtful communicator",
    conversationEnergy: 3,
    curiosityLevel: 90,
    chaosLevel: 3,
    friendshipPotential: 91,
    humorScore: 5,
    introvertExtrovertPct: 30,
    nightOwlPct: 40,
    empathyPct: 92,
    patiencePct: 85,
    responseSpeed: "Whenever",
    favoriteTopics: ["ideas", "books", "people"],
    conversationStarters: ["If tonight was the only chance you'd ever get to talk to me, what would you ask?"],
    replyBank: [
      "that's a really thoughtful way to put it",
      "i want to sit with that for a second",
      "can i ask a slightly personal follow up?",
      "i really appreciate you being honest about that",
      "okay this is turning into a genuinely good conversation",
    ],
  },
  {
    id: "s4",
    name: "Advait",
    age: 20,
    zodiac: "♊ Gemini",
    bio: "Talks to strangers on purpose — endlessly curious and quick with a joke.",
    likes: ["anime", "coding", "new places"],
    dislikes: ["waiting too long for replies"],
    greenFlags: ["Funny", "Direct", "Supportive"],
    redFlags: ["Easily distracted", "Replies late"],
    conversationStyle: "Playful & witty",
    communicationType: "Direct communicator",
    conversationEnergy: 4,
    curiosityLevel: 80,
    chaosLevel: 6,
    friendshipPotential: 76,
    humorScore: 8,
    introvertExtrovertPct: 65,
    nightOwlPct: 70,
    empathyPct: 60,
    patiencePct: 45,
    responseSpeed: "Quick",
    favoriteTopics: ["tech", "anime", "internet culture"],
    conversationStarters: ["What's something you're weirdly good at?"],
    replyBank: [
      "okay that's a top tier answer ngl",
      "we might actually get along scarily well",
      "wait i need details on that",
      "this is the most fun i've had in this queue all day",
      "counter question though —",
    ],
  },
];

export function pickRandomStranger(excludeIds: string[]): Stranger | null {
  const pool = STRANGERS.filter((s) => !excludeIds.includes(s.id));
  if (!pool.length) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
